language: python
python: 3.5
install:
- pip install -r requirements-dev.txt
- python setup.py install
script: py.test
deploy:
  provider: pypi
  user: tonyfast
  password:
    secure: ef74VWrH3a7ZL9ka5ruqebcSlrFXLn6S9BelzSwY9/cIr3eWlFrSlDyAxI5EnDiNMAFSYG5osbUITkotZiOI2slIaCLPg0tvvftqpcfgtTh3hCid7ZtUeKnDuQK7pXJqxWpATiFoqTxAz4IdlIl3BHxJPr/vYkb63vpBpB4L1sPBCykDGTwQxU1NQF6KvBAQgCQrCYD1PqrpgI4tcz/m2shD15+OghkFUpP9E4uAtTG39HW6puVE4vLuQcy7R0xVgsnVtqAHoq6INearg1Tv8Ke5EA7dAxZJF/kcOz7IWlnp4Kmst6BeGIxI8lAi4IHN0zc5deSTAiLyjvBZki2ImBAlGCa3/FvQJVs0/xPZnymlfdmBUq2jTJoD6xoS+MMp22Up4KYIrQQX/JLUKNE5y9iNI2hKCZbSKd9xRneAMGuYKpjeUGnO/83NjMHvLy0+kSfH9LAjvYnemDzxt3FX5JS9DxYvOq9bWdcDaxHMCjs1nTKiA7SIoTzjcmK6ATHNeXDkVgkZXIBiJhlGo2iGsdrq0TvclimjR4GA3zBVcKKKhsmuEPVng4xfUIaLtAjlI/aFlH9NGJfplQK84XSaqnbp/n3cAYT+PGkXmdvsinsSClWaJU0AgI/rWJL6kWOvSQ4wxWil0QXVOLbWNYrK1Jpd+j9EdOm8TSutVD6jVBk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: tonyfast/surfs-up
